name: Continuous integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test_demos_no_error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: pip3 install --no-cache-dir -r requirements.txt
      - name: Test the writing demo
        run: python3 demos/demo_write.py
      - name: Test the reading demo
        run: python3 demos/demo_read.py
      - name: Test the reading demo with no paths given to read_reprs
        run: python3 demos/demo_read_no_paths.py
  test_pypi_package_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Test the build
        run: python3 .github/workflows/test_pypi_package_build.py
